# Every element with (Environment) means that they must be specified by the environment

app:
  valid_directory_name_regex: \A[A-Za-z0-9_\-\.\+=]+\z
  root_directory_name: __ROOT__

auth0:
  client_id: # (Environment) ID of the auth0 client
  client_secret: # (Environment) secret of the auth0 client

  known_oauth_providers:
    - github
    - google-oauth2

postgres:
  host: # (Environment) hostname of postgres server
  username: # (Environment) username to use
  password: # (Environment) password to use
  database: # (Environment) the database name to connect to
  port: # (Environment) the port on 'host' on which to connect