jwt:
  client_id: LbGid9glzIogma9BHpJYvy4svR5A1lGa
  client_secret: n0k5MnqEGTKTLmj2OSgKFwmHjV3S1gh85IScxQpCgCnzR8gtQmMiaRvv7jEAgBVA
  issuer: https://auth0.smartdirect.com

postgres:
  host: aws-us-east-1-portal.12.dblayer.com
  username: admin
  password: QTOSPDMAEIIJHVTT
  database: compose
  port: 15340