jwt:
  client_id: LbGid9glzIogma9BHpJYvy4svR5A1lGa
  client_secret: <%= ENV['SMD_JWT_SECRET'] %>
  issuer: https://auth0.smartdirect.com

postgres:
  host: localhost
  username: smartdirect
  password: smartdirect
  database: smartdirect_dev
  port: 5432