jwt:
  client_id: <%= ENV['SMD_JWT_AUDIENCE'] %>
  client_secret: <%= ENV['SMD_JWT_SECRET'] %>
  issuer: <%= ENV['SMD_JWT_ISSUER'] %>

postgres:
  host: <%= ENV['SMD_DATABASE_HOST'] %>
  username: <%= ENV['SMD_DATABASE_USER'] %>
  password: <%= ENV['SMD_DATABASE_PASSWORD'] %>
  database: <%= ENV['SMD_DATABASE_DB'] %>
  port: <%= ENV['SMD_DATABASE_PORT'] %>