jwt:
  client_id: <%= ENV['SMD_JWT_AUDIENCE'] %>
  client_secret: <%= ENV['SMD_JWT_SECRET'] %>
  issuer: <%= ENV['SMD_JWT_ISSUER'] %>

postgres:
  host: <%= ENV['SMD_DATABASE_HOST'] || 'localhost' %>
  username: <%= ENV['SMD_DATABASE_USER'] || 'smartdirect' %>
  password: <%= ENV['SMD_DATABASE_PASSWORD'] || 'smartdirect' %>
  database: <%= ENV['SMD_DATABASE_DB'] || 'smartdirect_dev' %>
  port: <%= ENV['SMD_DATABASE_PORT'] || '5432' %>