jwt:
  client_id: <%= ENV['SMD_JWT_AUDIENCE'] %>
  client_secret: <%= ENV['SMD_JWT_SECRET'] %>
  issuer: <%= ENV['SMD_JWT_ISSUER'] %>

postgres:
  host: localhost
  username: smartdirect
  password: smartdirect
  database: smartdirect_test
  port: 5432